spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/toddo
    username: ###
    password: ###
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
hibernate:
  show_sql: true

jwt:
  secret: ###
  jwtExpirationMs: 86400000